### ISSUE TITLE
JAC the jobs

### ISSUE THREAD

**Issue by willbarton** [cfpb/hackathon#13]
@marcesher @imuchnik 

Hands-on workshop with [Jenkins as Code](https://github.com/cfpb/jenkins-automation)?

More fleshed-out ideas forthcoming.

**Comment by imuchnik** [comment]
Open to it being a working session for those who want to get more into it. Not comfortable with people taking it on as a 'Hack project', unless they do not care to ever see it merged.

**Comment by imuchnik** [comment]
Definitely maybe.

**Comment by OrlandoSoto** [comment]
this would be a fun workshop :)

**Comment by sleitner** [comment]
@imuchnik @OrlandoSoto @vickumar1981 let's talk about this during sprint planning?

**Comment by vickumar1981** [comment]
I like it.

**Comment by OrlandoSoto** [comment]
ok

**Comment by cfarm** [comment]
We're no longer doing workshops at this event so as not to conflict with the regroup lightning workshops that are planned - recommend you reach out to @designlanguage if you'd like to give this there!

**Comment by imuchnik** [comment]
I am already teaching another workshop. I am more than happy to assist anyone with JAC before, during and after the regroup.
