### ISSUE TITLE
README Roulette

### ISSUE THREAD

**Issue by willbarton** [cfpb/hackathon#14]
Inspired by out [README Refresh Day](http://cfpb.github.io/articles/readme-refresh-day/) in January, how about a rolling README Roulette, where people can take a break from the project they're working on, draw a README out a hat, and spend 30 minutes or some short amount of time improving it?

These could be CFPB, 18F, anyone's READMEs.

**Comment by cfarm** [comment]
I love it

I nominate this hat:

http://www.amazon.com/Elope-Inc-Kids-Birthday-Cake/dp/B000034DLD/ref=sr_1_5?ie=UTF8&qid=1452023648&sr=8-5&keywords=internet+hat
![cool hat](http://ecx.images-amazon.com/images/I/417DzJoUZWL._AC_UL115_.jpg)

**Comment by ascott1** [comment]
This is a fantastic idea @willbarton

**Comment by willbarton** [comment]
Do we want to have two hats? One hat has people's names in it, the other has projects. Every 30 minutes or so we pull out 3-4 names and one project? Or is that too involuntary?

**Comment by willbarton** [comment]
Anyone want to propose READMEs? Otherwise the hat\* will have all the READMEs.  ALL OF THEM.

\* Hat has yet to be determined to be an actual hat.

**Comment by willbarton** [comment]
So, here's the basic overview of README Roulette:

Volunteer!

https://github.com/cfpb is our public open source presence. The READMEs for all the repositories there are our front-door, and will be the first impression anyone has of our open source work.
- Take 15-30 minutes, pick a random public repository from the board
- Read the README and ask yourself the following questions:
  - Do I know the purpose of this repository?
  - Do I know roughly who this repository is for?
  - Do I know roughly how I'd get started with the contents of this repository?

If the answer to any of those is no, then take a little bit of time and try to improve the README! 

The goal is to open a pull request or file an issue with suggested changes, but if you can't figure out how to improve the readme at all (i.e. you're still left wondering what the repo is supposed to have in it), open an issue and report that too!

I'll have a timer running, so don't spend too much time on it — someone visiting a repo with a bad README certainly won't!
