### ISSUE TITLE
Finance +  Math + Code = CapitalJS

### ISSUE THREAD

**Issue by cfarm** [cfpb/hackathon#19]
[CapitalJS](https://capital.js.org/) is a library of financial formulas written in JavaScript. Developers can pass objects with parameters to perform common financial calculations such as interest, return on investment, or amortization.

Ways to contribute:
- [Propose a formula](https://github.com/CapitalJS/capitaljs/issues/7) to be added to the library, and define the math for it (requires financial/math skills)
- Add new formulae to the [module library](https://github.com/CapitalJS/capitaljs) using Test-Driven Development (requires JavaScript or programming knowledge)
- [Design a logo for the project](https://github.com/CapitalJS/capitaljs/issues/8) (requires graphic design skills)
- [Standardize existing modules following API specs](https://github.com/CapitalJS/capitaljs/issues/13), including updating tests and the [api](https://github.com/CapitalJS/api) project. (requires JavaScript/programming skills)

**Comment by paladugus** [comment]
Hi, I'd like to join if that's still possible.

**Comment by cfarm** [comment]
@paladugus definitely! we'll see you Wednesday.

**Comment by mistergone** [comment]
I'm totally hacking on this on Thursday.
