### ISSUE TITLE
CFPB progressive web app shell

### ISSUE THREAD

**Issue by ascott1** [cfpb/hackathon#20]
## Project idea

Design and develop the shell of a progressive web application, that could potentially be used for future CFPB projects.
## More detail

I'm pretty excited about the idea of progressive web apps and think the set of technologies they represent fit well into our stack (once we're serving everything over https).

Here's the main idea (from Alex Russel): 

> **Responsive:** to fit any form factor
> **Connectivity independent:** Progressively-enhanced with Service Workers to let them work offline
> **App-like-interactions:** Adopt a Shell + Content application model to create appy navigations & interactions
> **Fresh:** Transparently always up-to-date thanks to the Service Worker update process
> **Safe:** Served via TLS (a Service Worker requirement) to prevent snooping
> **Discoverable:** Are identifiable as “applications” thanks to W3C Manifests and Service Worker registration scope allowing search engines to find them
> **Re-engageable:** Can access the re-engagement UIs of the OS; e.g. Push Notifications
> **Installable:** to the home screen through browser-provided prompts, allowing users to “keep” apps they find most useful without the hassle of an app store
> **Linkable:** meaning they’re zero-friction, zero-install, and easy to share. The social power of URLs matters.
### Further reading:
- [Progressive Web Apps: Escaping Tabs Without Losing Our Soul](https://infrequently.org/2015/06/progressive-apps-escaping-tabs-without-losing-our-soul/)
- [Progressive Web Apps](https://developers.google.com/web/progressive-web-apps)
- [Introducing Pokedex.org: a progressive webapp for Pokémon fans](http://www.pocketjavascript.com/blog/2015/11/23/introducing-pokedex-org)
## Who could we use on this project?
- FEWDs for implementing service workers, manifest, Capital Framework, and JS niceties
- Designers for designing the application shell
- BEWDS for integrating it all with a Django app(?)

**Comment by Scotchester** [comment]
![Your ideas are intriguing to me and I wish to subscribe to your newsletter.](http://cdn.meme.am/instances/250x250/58426240.jpg)

**Comment by willbarton** [comment]
And then integrate it with https://github.com/willbarton/cfpb-django-app for the win!

**Comment by ascott1** [comment]
> And then integrate it with https://github.com/willbarton/cfpb-django-app for the win?

Exactly!

**Comment by stephanieosan** [comment]
What does it mean to design the application shell?

**Comment by ascott1** [comment]
@stephanieosan take a look at this article: https://developers.google.com/web/updates/2015/11/app-shell

It's a pretty simple example, but I think it could give an idea for the types of design elements we could create.

**Comment by ascott1** [comment]
I still :heart: this idea, but I don't plan on pitching it as a hackathon project. Closing!
