### ISSUE TITLE
Owning a Home' "explore interest rates" as a native mobile app

### ISSUE THREAD

**Issue by ascott1** [cfpb/hackathon#24]
Owning a Home's rate checker is inanely awesome and could be a really cool native mobile app that uses's the web site's API. We could use a web technology based app development tool (such as React Native, Cordova, or Ionic) to leverage existing skill sets and build a cross platform app. 
## Team needed
- Designers! What does a native CFPB app look like?
- Developers! To choose a mobile app development suite and prototype the experiemce

**Comment by imuchnik** [comment]
@ascott1 Sign me up!

**Comment by marteki** [comment]
Ooooh!

If we can get this to show on a device, I would guerrilla usability test it so much.

**Comment by ascott1** [comment]
> If we can get this to show on a device, I would guerrilla usability test it so much.

Could it be paper prototyped first thing in the morning for usability testing?

**Comment by marteki** [comment]
YES

**Comment by ascott1** [comment]
:heart_eyes:

**Comment by stephanieosan** [comment]
Sorry–what's the benefit of making it into a native app?

**Comment by mebates** [comment]
I wondered the same @stephanieosan

**Comment by ascott1** [comment]
> Sorry–what's the benefit of making it into a native app?

A few reasons off the top of my head:
1. Optimize the mobile UI
2. Remove unecessary cf.gov header/footer/nav to maximize tool real estate on a device
3. Work offline (or at least save previous results)
4. Quickly bookmark it for pulling out when sitting in the office of a lender (sure mobile bookmarks are a thing, but not many people use them)
5. Prototype what a CFPB native mobile app might look like

**Comment by ascott1** [comment]
I feel the need to expand on this one:

> Optimize the mobile UI

Currently we have things like the text introduction and some really static user values (credit score) that a user may not want to see each time they use this on a mobile device, but they make a lot of sense as they are on a responsive website (though we could store some values locally so a user wouldn't have to adjust them on each visit unless they wanted to).

Specifically the CFPB site header/nav and introduction to the tool use all of the available space on a mobile device. Here's a screenshot of the tool on an iPhone 6:

![screen shot 2016-01-08 at 12 32 40 pm](https://cloud.githubusercontent.com/assets/212533/12204755/2785c910-b604-11e5-825b-3aa52f4a82f2.png)

But mostly I just think this would be a cool thing to experiment with that's the kind of space this event gives us (even without a clear business need).

**Comment by imuchnik** [comment]
@ascott1 @mebates @stephanieosan 
To add some other benefits:
It lets developers work on some  other tech stack than what we do everyday, which we perceive as fun (pathetic, I know, but true).
I hesitate to remind everyone, but this is a hackathon project, and as such needs to be fun. 

The project may or may not have a lifespan longer then a day or two, but it helps us grow, expand our skill set and expose ourselves to different paradigms. That experience has long lasting positive impact.

**Comment by contolini** [comment]
:+1: to @imuchnik's and @ascott1's comments.

:-1: to @stephanieosan and @mebates for raining on our parade.

:japanese_ogre: to my comment.

Oh and @marteki gets a :sunglasses:.

**Comment by contolini** [comment]
Given our locked-down machines, you may run into problems installing and running android-sdk.

**Comment by imuchnik** [comment]
@contolini I have successfully installed Android Studio and all the needed NDK. We should be ok. 
But we can also use something like Ionic.

**Comment by willbarton** [comment]
Why not do some magical front-end mobile app thingie, like React Native or Ionic?

**Comment by imuchnik** [comment]
@willbarton not off the table

**Comment by ascott1** [comment]
Exactly @willbarton!

**Comment by contolini** [comment]
React Native, Ionic and Cordova all use android-sdk under the hood.

**Comment by imuchnik** [comment]
@contolini  are you saying:"cut the middleman"?
Android is java based and is verbose and cumbersome. These frameworks may add some "sugar" when dealing with Android.

**Comment by contolini** [comment]
@imuchnik No, I fully support any of the above frameworks. I just advise that participants install all required software in advance to confirm our laptops support whatever framework is chosen.

I think we'll also need the latest version of Xcode.

**Comment by imuchnik** [comment]
@contolini  Got it. Again Android Studio packages things nicely.  I would recommend using Genymotion for the simulator though. I do have Nexus 9, that Google generously gave for development and happy to offer it for "guerilla user testing" (@marteki, I am looking at you)

**Comment by cfarm** [comment]
@mthibos thoughts??

Also this application is now called "Explore interest rates" not the rate checker.

**Comment by mthibos** [comment]
Hey folks!  Just got wind of this!  Fun times  :grinning: 

I don't want to get :frowning: faces from @contolini for parade-raining.  However, I can say with absolute certainty that this would be a controversial project internally and externally.  It's hard for me to imagine stakeholders embracing us publishing this app, at least not without a lot of additional work.

But... that doesn't mean it's not a good use of hackathon time, if it sounds like fun to y'all.  :grinning:

**Comment by contolini** [comment]
![](https://d2pi0bc9ewx28h.cloudfront.net/n0seiv1/u9Rln8mjm/tumblr_lmu894rxom1qbar4bo1_500.gif)

**Comment by imuchnik** [comment]
ok, we won't publish.
