### ISSUE TITLE
Name ideas

### ISSUE THREAD

**Issue by cfarm** [cfpb/hackathon#3]
- Collab
- GovMake
- GovBuild
- GovApps
- CFPB Open Tech Day
- ~~Beta.gov~~ (ok this is taken by gov.uk)

**Comment by cfarm** [comment]
https://github.com/18F/web-design-standards/issues/10

**Comment by Scotchester** [comment]
Please dear me, not _another_ thing named "Collab".

**Comment by willbarton** [comment]
We have a winner!

**Comment by KimberlyMunoz** [comment]
CollabCollab

**Comment by cfarm** [comment]
Collab.ly

**Comment by cfarm** [comment]
Cahoots

**Comment by cfarm** [comment]
Collaboratory

**Comment by willbarton** [comment]
> Collaboratory

I really do like this word. We have to find a way to use it.

**Comment by cfarm** [comment]
CFPB HACK DAY IT IS

**Comment by contolini** [comment]
Collab?

**Comment by Scotchester** [comment]
@contolini 

![](http://www.reactiongifs.com/r/nsh.gif)
