### ISSUE TITLE
Brainstorm: Games for building kids' money skills

### ISSUE THREAD

**Issue by Schlachtmeyer** [cfpb/hackathon#31]
We have a great opportunity to help parents build their kids' money skills, habits, and attitudes -- without making it a huge chore.

Let's brainstorm for ways to hack existing games or create "expansion packs" for them, to help parents & caregivers build age-appropriate money activities into daily life. Board games or online games, doesn't matter.

We have an entire body of knowledge and research around what kids need at different stages of their development -- and games are a great way to put this information into practice.

Optional: If you're excited about background reading, here's our report on Financial Well-Being for adults (http://www.consumerfinance.gov/reports/financial-well-being/) and here's a journal article (http://onlinelibrary.wiley.com/enhanced/doi/10.1111/joca.12068/) that we commissioned on how children develop financially.

**Comment by willbarton** [comment]
This would be awesome.

**Comment by Schlachtmeyer** [comment]
Looking for anyone who is interested in brainstorming this subject -- whether you're interested in kids, games, financial education, prototyping, or you're a parent or primary caregiver.

**Comment by kurzn** [comment]
Or all of the above! :) Sounds like a lot of fun.

**Comment by tanderegg** [comment]
Sounds like fun, I'm in!
