### ISSUE TITLE
New Relic improve-a-thon

### ISSUE THREAD

**Issue by marcesher** [cfpb/hackathon#32]
We should have New Relic installed on all cf.gov-related production servers by the time of the hackathon.

I propose a project where we use New Relic to tell us parts of our app that are slow, or erroring, and we try to fix some of them.

Expected Outcomes:
1. Gain experience using New Relic to identify performance problems in an application
2. Create a backlog of improvement work, based on what NR identifies
3. Potentially fix one or more problems we find

**Comment by jonathanwcrane** [comment]
I am definitely interested in this one.  I'll check to see if I'm able to participate.

**Comment by KimberlyMunoz** [comment]
I'm interested in this one as well, especially if there's some front end performance improvements we can do as a result of this project.
