### ISSUE TITLE
Better Capital Framework documentation

### ISSUE THREAD

**Issue by ascott1** [cfpb/hackathon#33]
Right now Capital Framework's documentation is a huge pain point. With the roll out of version 3.0 (aka Voltrazord) it's also painfully out of date. We have a proposal for [improved documentation pages](https://github.com/cfpb/capital-framework/issues/242) as well as [integration with the design manual](https://github.com/cfpb/capital-framework/issues/243), but they haven't moved beyond those stages.
## Project

Design, prototype and user test better CF documentation.
## Team members
- FEWDs who are familiar with CF or willing to dive in to prototype and translate existing docs
- Content peeps who are willing to help improve the site content
- UXers for improved site UX and user testing
- Designers to make the design moar betterer and help with user testing

**Comment by keelerr** [comment]
Currently, I know almost nothing about Capital Framework, but I'm happy to help with the UX—whether it's some IA work or user testing.

**Comment by ascott1** [comment]
Yay @keelerr!

**Comment by cfarm** [comment]
:+1:

**Comment by mistergone** [comment]
:memo: :octopus: :+1:

**Comment by ascott1** [comment]
Here are a few example UI framework doc sites for research purposes:
- https://github.com/thoughtbot/bitters#using-bitters
- http://www.basscss.com/docs/
- http://bourbon.io/docs/
- http://uspto.github.io/designpatterns/1.x/docs/index.html
- https://getbootstrap.com/
- http://foundation.zurb.com/
- https://milligram.github.io/index.html
- http://purecss.io/
- https://imperavi.com/kube/
