### ISSUE TITLE
Stand up MatterMost for chat

### ISSUE THREAD

**Issue by willbarton** [cfpb/hackathon#34]
For the more systems admin-ish hackathon project, what do people think of trying to stand up MatterMost in place of Jabber/Adium? 

http://www.mattermost.org/

**Comment by Scotchester** [comment]
Interested.

**Comment by imuchnik** [comment]
I like it. Count in me in.

**Comment by jonathanwcrane** [comment]
This is done!

**Comment by ascott1** [comment]
:tada: Maybe this can be replaced by some chat bot projects?

**Comment by jonathanwcrane** [comment]
We could build an AI that passes the Turing test.

Eventually we could build an AI that chats with consumers in real time about their complaints.

**Comment by sephcoster** [comment]
I'd be in to assist with some customizations and changes. In addition to bots, I think customizations of our alerts, entry pages, and perhaps attempting a new Go build with these customizations could be awesome.

**Comment by sephcoster** [comment]
Possible Hackathon Goals:
- SSL on the Server (enables Hubot User, other features)
- Updated Static React templates for the organization
- Cleanup image generation scripts / customize
- GHE / Jira / Jenkins automation via hubot
- Reactji feature 
- User Guides / Community Updates
- Updated Bot Responses

**Comment by Scotchester** [comment]
Where applicable, we should endeavor to contribute to the core platform, or set ourselves up to do so. I'm still getting my head around their feature pipeline and development process, but I did come across this:

Reacji feature request: https://mattermost.uservoice.com/forums/306457-general/suggestions/11206161-add-emoji-reactions

**Comment by Scotchester** [comment]
Other goal ideas:
- Improve design of threaded comments
- Redirect mattermost's URL to `/cfpb` if not logged in.
- Get some better looking emoji (hands, especially)
- [Add support for adding custom emoji](https://mattermost.uservoice.com/forums/306457-general/suggestions/11206074-add-ability-to-add-custom-emojis)

**Comment by Scotchester** [comment]
- Always-visible list of channel members (preferably in a right-hand sidebar, like Slack).

**Comment by marteki** [comment]
On the emoji theme: support Unicode 8's diverse emoji.

**Comment by marteki** [comment]
Other feature requests collected over the last week:
- native check-spelling-as-you-type in the message entry form field
- a "XX new messages" message at the top where if you click it anchors you back up to where the new ones are
- improve user autocorrect, to key off subphrases in user names

**Comment by OrlandoSoto** [comment]
trending topics in the sidebar, or ability to ask the bot what topics are trending then get response links via PM.  
e.g. trending topic: anyone having problem with Citrix right now?

**Comment by OrlandoSoto** [comment]
feature request: option to display channels that I interact with most instead of (or in addition to) alphabetical listing,, e.g. my frequent/fave channels

**Comment by marteki** [comment]
@lgdean and I have been noodling on emojis: https://gist.github.com/marteki/b8133b0de790c4065abd60f18472d617

And did some whiteboarding, because why not:

![emoji whiteboard](https://cloud.githubusercontent.com/assets/1183435/14540248/18aeab24-0252-11e6-932e-f371838e72ae.jpg)
