### ISSUE TITLE
CFPBot wishlist items?

### ISSUE THREAD

**Issue by willbarton** [cfpb/hackathon#35]
For the hackathon participants who just want to write CoffeeScript, we could hack on [CFPBot](https://github.com/cfpb/CFPBot).

Possible tasks:
- Eardropping timeout. Don't keep repeating the same thing over and over again within a certain amount of time?

**Comment by cfarm** [comment]
Meeting reminders. Chat commands to turn on/off reminders for a weekly meeting that CFPBot would yell at us

**Comment by higs4281** [comment]
#22 could be folded into this issue

**Comment by willbarton** [comment]
@higs4281 yes! Sorry, on first reading "acrobot" was "acrobat" and I thought it was a PDF thing.

**Comment by higs4281** [comment]
i shouldn't use that name

**Comment by willbarton** [comment]
Or I should learn to read 😜

**Comment by sephcoster** [comment]
I think project specific github notifications will be critical. In the past, having Pull Request and Merge messages sent to the project room was awesome for informational purposes.
- https://github.com/hubot-scripts/hubot-github-repo-event-notifier
- https://github.com/hubot-scripts/hubot-ghe

Similarly, might be useful to tap into some Jira / story-based automation. Further Jenkins / Travis updates could also be nifty, especially in a project-specific context.
- https://github.com/github/hubot-scripts/blob/master/src/scripts/jira.coffee

**Comment by willbarton** [comment]
~~Respond to "guys" with a random choice from a list of possible replacements, more like slackbot, to avoid repeating the same response over and over.~~
