### ISSUE TITLE
UnityBox nightly builds

### ISSUE THREAD

**Issue by marcesher** [cfpb/hackathon#36]
A well-known, long-standing problem with UnityBox -- and every single VM-based or local development environment we've had since I've been with the CFPB -- is that it gets stale rather quickly. With so many developers contributing so many different things to the cf.gov platform, it's inevitable that something, somewhere, is going to stop working in UnityBox (or, likely, any future automations we build to replace UB, docker-based or otherwise).

We've wanted to do a nightly automation of UnityBox and other Vagrant-based builds for a while, but it's always either been backburnered or, when we prioritize it, realize that we don't have the physical hardware we need to build Vagrant VMs.

I'm pretty sure we can figure out the hardware problem, and what we need are a few good humans to chip in to Jenkins-automating a nightly UnityBox build.

This will not fix things starting to break in UB; but it will alert us immediately, rather than months later.

**Comment by willbarton** [comment]
This is a fantastic idea.

Is there any way we can have UnityBox builds triggered with our other dev Jenkins builds? So that each PR attempts the build on a UnityBox too? Or something to that effect?

**Comment by higs4281** [comment]
reprovision on every build? that would be sweet, especially if provisioning
is faster without all the forking.
