### ISSUE TITLE
Economic and Psychological Experiments in oTree

### ISSUE THREAD

**Issue by DavZimmer** [cfpb/hackathon#38]
I am a research assistant in the Behavioral Decision Making Section in the Office of Research.  We heard about your hackathon when presenting about our hope for getting some design assistance with our laboratory experiment materials.  I should be around for most of the day to participate.  

In the Office of Research we are creating economic and psychological based games to be used in our lab studies.  These games will help us learn about individuals and their decision-making processes.  We just completed our first experiment involving buyers and sellers for an imaginary good.  We used zTree (http://www.ztree.uzh.ch/index.html) which is a free, but proprietary program.  For future experiments we are hoping to switch to a more robust platform, likely oTree (http://www.otree.org/), which is based on python, html/css/javascript, and django.  

Unfortunately the oTree platform is quite new and so they do not have a lot of experiments that have  created complex games.

There are a few directions we could take this.  The first could be to create the basic structure of our game in zTree using the oTree platform since the basic structure of the game will definitely be used in the future.  We could also create a fairly simple game that has a lot of unusual features, such as dynamic graphs, to explore a lot of the cool features oTree can offer.

In general the experimental tasks will eventually be loaded onto a server at a university and run with subjects.

**Comment by mebates** [comment]
:tada: 
Thanks for jumping in David, and the Office of Research!

To be clear, you're looking for developers with experience in python and Django, right? 

If any designers want to help, they can jump in, too. It would be cool to apply a light Capital Framework styling to the experiment. 

Make sure you come to room 701 at 9 am to pitch your project!

**Comment by elizbond** [comment]
:+1: This will be an exciting project!

**Comment by DavZimmer** [comment]
Yep, developers with experience in python and Django would be great.  Almost all of my programming experience is in python.
