### ISSUE TITLE
Convert cf-icons from an icon to SVG for better accessibility

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/hackathon#41]
Right now, we serve most of our icons with an icon-font which has a few downsides, especially for accessibility.
- They don't allow people to change their fonts
- When they occupy the same namespace as emojis, weird stuff happens with screenreaders
- Avoiding icon fonts avoids the flash of sudden text
- SVGs make it easier to add alt text
## Articles

[Seriously don't use icon fonts](http://blog.cloudfour.com/seriously-dont-use-icon-fonts/)
[Delivering Octocons with SVGs](https://github.com/blog/2112-delivering-octicons-with-svg)
[Death to Icon Fonts -- Fast forwarded to the part on screenreaders](https://youtu.be/9xXBYcWgCHA?t=7m36s)

(h/t to @jimmynotjim for bringing this up in chat!)

**Comment by contolini** [comment]
ohyespleasesomeonedothisone :heart_eyes:

**Comment by frank0631** [comment]
I won't be there. But here is a quickly generated SVG from vectormagic.com of the CFPB logo to get you started (had to save it as a text file) 
[cfpb-logo.txt](https://github.com/cfpb/hackathon/files/217995/cfpb-logo.txt)
