### ISSUE TITLE
Find creative ways to use and/or visually present CFPB's Complaint Narratives

### ISSUE THREAD

**Issue by hcheng001** [cfpb/hackathon#45]
As stated, complaint narratives was recently added in the public complaints data CFPB publishes. Want to find creative ways to make use of this data, and visually present the findings through Tableau and potentially other data visualization tools. The BI Team is making the proposal and we have sponsors from Consumer Response's Reporting Team joining on the effort as well. So anyone who can help in anyway is welcome to join us.

**Comment by cfarm** [comment]
I like this idea very much. Part of my goal with the the project I'll be working on (see #42 Consumer complaint API workshopper) is to build a data visualization example using the d3.js library with consumer complaint narratives, so I am looking for good ideas on how to present that data and would love to work with your team on this.

**Comment by cfarm** [comment]
This project needs help with:
- **Visual design**. What type of visualization can we use to present the narratives in a compelling way? 
- **User experience design**. How can we present the narratives data in an understandable way? Is a data visualization even the best way to present this information?

**Comment by amycesal** [comment]
This was really close to what my small project team for immersion worked on. I'm happy to help hack on this.
