### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by cfarm** [cfpb/hackathon#6]
- Should we have one solid theme to organize the projects around? 
- Let's brainstorm some ideas of what the theme could be.

OR 
- Is it enough to have some well-defined projects and just call it a fedgov theme and be done with it.

Discuss.

**Comment by cfarm** [comment]
Some theme ideas that came out of our first meeting:
- CCDB Data
- HMDA Data

**Comment by contolini** [comment]
As @ascott1 mentioned, incorporating US Web Design Standards is a great idea.

**Comment by contolini** [comment]
$$$ theme
- Simple consumer financial planning apps using our public data or just general financial literacy tools.
- [CapitalJS](http://capital.js.org/). We can make a list of formulae missing from CapitalJS to let folks implement. Would be a great intro-to-TDD-and-Node.js project.

**Comment by marcesher** [comment]
@cfarm Some questions:
1. Does it need to be a theme? 
2. Does it need to be projects where **new** things are made?

Or, if folks chose, could the theme be "Fix existing things"? Rather than work on HMDA data (I've been doing that for 2 years; I can't think of any greater turn-off, personally, than working on HMDA, which was the subject of our first hackathon in 2013), could I use this time to grab issues from govcode.org labeled "help wanted" or "newbie friendly" or whatever and simply work on improving existing software rather than putting yet more new stuff into the world? Could I pay back technical debt rather than create new technical debt?

**Comment by ascott1** [comment]
>  could I use this time to grab issues from govcode.org labeled "help wanted" or "newbie friendly" or whatever and simply work on improving existing software rather than putting yet more new stuff into the world? Could I pay back technical debt rather than create new technical debt?

I really love this

**Comment by Scotchester** [comment]
> >  could I use this time to grab issues from govcode.org labeled "help wanted" or "newbie friendly" or whatever and simply work on improving existing software rather than putting yet more new stuff into the world? Could I pay back technical debt rather than create new technical debt?
> 
> I really love this

:+1::+1:

**Comment by KimberlyMunoz** [comment]
I think it's good to have a mix of the two. At 18F's hackathon, they mostly had projects that were already made and ready for people to contribute on, but some folks wanted to just work with data and make something new and small.

**Comment by cfarm** [comment]
I like what Kim and Mark are sayin. 

What if we had a Julython-type tracker for the Govcode help wanted issues? It would be cool to brag about how many issues got closed during the event, and get some visualizations of the work done.

**Comment by cfarm** [comment]
I like the idea of having a theme that would help us attract subject matter experts from CFPB to the event. Let's plan to pick a strong theme based on CFPB's work, with some suitable projects prepared in advance, while making it clear that attendees have the freedom to present their own project ideas too.

Theme ideas so far: 
- CCDB Data
- $$$ (Finance? what)
- ~~HMDA~~ no bc done already
- Student Loans

**Comment by contolini** [comment]
> What if we had a Julython-type tracker for the Govcode help wanted issues? It would be cool to brag about how many issues got closed during the event, and get some visualizations of the work done.

Making it less of a hackathon and more of a game is an interesting idea.
1. Participants show up and form teams.
2. We present a list of XXXXX open GH issues taken from Govcode (or maybe we just point people to https://www.govcode.org/issues).
3. The team that closes the most issues by the end of the event wins.

Bonus awards for most creative solution, most impactful contribution, etc.

Participants won't have GH permission to actually close the issues but judges can determine if they were successfully "fixed".

**Comment by ascott1** [comment]
> Participants won't have GH permission to actually close the issues but judges can determine if they were successfully "fixed".

Maybe it could be based on PR's submitted?

**Comment by contolini** [comment]
> Maybe it could be based on PR's submitted?

True, it's unlikely a team would submit a PR to a stranger's repo that was devoid of utility.

**Comment by ascott1** [comment]
My initial reaction is that this would encourage people to seek out the easiest to fix issues, but with some more thought that's not really a bad thing.

**Comment by marcesher** [comment]
@ascott1 I don't think fixing simple things is a bad thing at all. 

As Horton says, roughly: "A fix is a fix no matter how small"

**Comment by jimmynotjim** [comment]
:musical_note: Boil that bug fix! :musical_note:

**Comment by OrlandoSoto** [comment]
@cfarm HMDA is crossed out above (no bc done already) but it still appears as a choice in the hackathon survey (https://docs.google.com/forms/d/1V8847N8LpnkV-9EWRvpxwjMwhEYQIt9ttflz2ccP7JQ/viewform), we should probably remove it from the google doc if it's not a valid suggestion?

**Comment by willbarton** [comment]
via @marcesher: 💪🇺🇸💻

**Comment by cfarm** [comment]
Govcode + fixing things is the theme.
