### ISSUE TITLE
Workshops

### ISSUE THREAD

**Issue by contolini** [cfpb/hackathon#7]
Current workshops planned:
- @mistergone Agile workshop
- @jimmynotjim UI Animation workshop
- @mebates Gif-A-Thon

Details to follow.

**Comment by mistergone** [comment]
Sorry I missed the last meeting - what's the schedule look like? How long do I have to workshop? :grin:

**Comment by contolini** [comment]
@mistergone No worries, nothing's been planned yet. I'm just gathering instructors and topics. I'll keep you in the loop.

**Comment by cfarm** [comment]
Can we get a "learn to code" workshop? "make a website?"
"how to tdd in capital.js"

**Comment by contolini** [comment]
We're no longer doing these workshops. Instead, everyone is encouraged to attend @designlanguage's lightning workshops that will take place the day before and after the hackathon, leaving Wednesday open for non-stop hacking.
