### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by cfarm** [cfpb/hackathon#8]
I'm thinking of adapting the [Nodeschool Code of Conduct](https://github.com/nodeschool/boston/wiki/Code-of-conduct) for us to use at the event.

For reference see also https://github.com/18F/code-of-conduct

**Comment by KimberlyMunoz** [comment]
Neither one of those Code of Conducts have a contact information for a point person/people for reporting problems. It's a small improvement we can add to make sure people who may not be familiar us know who to talk to.

**Comment by marteki** [comment]
Reminder from a non-organizer: the Code of Conduct page is still empty. :crying_cat_face:

**Comment by cfarm** [comment]
@marteki I know :(
